### ISSUE TITLE
Run without tor?

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/gotor#24]
Should there be an option to run without using socks5 proxy?

**Comment by ShAd0wJ** [comment]
The socks5 proxy is automatically used when using tor. You can see this if you look at the torrc.conf file most likely located in your /etc/tor directory if you're using linux or /prorams/ if you're using windows. You can also set these settings if you get the application proxychains on linux and look at the proxychains.conf file located in the /etc directory after download and tell it to use dynamic chaining instead of strict chaining, then change the setting from socks5 proxy to whatever you want and include this in the torrc.conf file. I don't recomend this though considering socks5 proxy is meant to protect you identity while using tor.
